### PR TITLE
mention on no coins aswell as coins

### PR DESCRIPTION
**Pull request by xela-zone**

### CODE REVIEW

**Comment by slice** [comment]
why the colon :screm:

**Comment by slice** [comment]
actually, we should actually just make it dm the user to avoid clutter

**Comment by xela-zone** [comment]
ok, i got that

**Comment by slice** [comment]
can you handle the user having dms disabled `except discord.HTTPException:` and then send them the balance in-channel?

oh, and also have it delete the command message too along with ignoring any perm errors from that

**Comment by 7bitlyrus** [comment]
I feel like there is a valid usage for posting the output in chat, for comparing and showing off coin counts. However, how a limit to that case, if implemented, is beyond what I've thought of so far.

**Comment by slice** [comment]
oops devon just impled this

**Pull request closed without merging**
